// src/CAD/CADGLTFList.jsx
const CADGLTFList = [
  {
    id: 1,
    title: 'Guitar Design',
    category: 'Product Design',
    year: '2022',
    description: 'Detailed CAD model of an acoustic guitar featuring advanced surface modeling techniques, assembly design, and precise component integration.',
    coverPhoto: '/Projects/Guitar Design Project/Guitar Design Project (1).jpg',
    gltfFile: '/CAD/Guitar/Guitar.gltf',
    color: '#ff6b35',
    modelColor: '#8B4513',
    tags: ['Product', 'Surface Modeling', 'Assembly'],
    transparency: 0
  },
  {
    id: 2,
    title: 'Bicycle Frame',
    category: 'Transportation',
    year: '2024',
    description: 'Complete bicycle frame model with accurate geometry and structural components demonstrating mechanical assembly principles.',
    coverPhoto: '/CAD/bike/bike-preview.jpeg',
    gltfFile: '/CAD/bike/bike.gltf',
    color: '#4ecdc4',
    modelColor: '#2C2C2C',
    modelRotation: { x: Math.PI / 2, y: 0, z: Math.PI / 2 },
    tags: ['Transport', 'Structure', 'Assembly'],
    transparency: 0
  },
  {
    id: 3,
    title: 'Burner Head Assembly',
    category: 'Thermal Systems',
    year: '2024',
    description: 'Standard Indian gas burner model designed for combustion simulation studies with geometric accuracy for CFD analysis.',
    coverPhoto: '/CAD/Burner Head/burner-perview.jpg',
    gltfFile: '/CAD/Burner Head/BurnerAssem.gltf',
    color: '#ff7b00',
    modelColor: 'rgb(69, 250, 241)',
    modelRotation: { x: Math.PI / 2, y: 0, z: Math.PI / 2 },
    tags: ['Thermal', 'CFD', 'Assembly'],
    transparency: 0
  },
  {
    id: 4,
    title: 'Propeller Blade',
    category: 'Aerodynamics',
    year: '2024',
    description: '10x4.5 propeller reconstructed from 3D scanning and point cloud data for aerodynamic analysis.',
    coverPhoto: '/CAD/Propeller/Propeller-preview.jpg',
    gltfFile: '/CAD/Propeller/Propeller.gltf',
    color: '#48cae4',
    modelColor: '#708090',
    modelRotation: { x: Math.PI / 2, y: Math.PI*3 / 2, z: Math.PI / 2 },
    tags: ['Aero', 'Scan', 'Analysis'],
    transparency: 0
  },
  {
    id: 5,
    title: 'S500 Drone Frame',
    category: 'UAV Systems',
    year: '2024',
    description: 'Reverse-engineered S500 quadcopter frame from 3D scans with 0.01mm tolerance including all mounting systems.',
    coverPhoto: '/Projects/Reverse Engineering of a S500 Drone/Reverse Engineering of a S500 Drone (1).jpg',
    gltfFile: '/CAD/S500-Frame/Base Frame.gltf',
    color: '#00ffa2',
    modelColor: '#afafaf',
    tags: ['UAV', 'Reverse Engineering', 'Precision'],
    transparency: 0
  },
  {
    id: 6,
    title: 'Roof Solar Panel',
    category: 'Renewable Energy',
    year: '2024',
    description: 'Parapet-mounted solar panel assembly designed for wind load analysis with adjustable tilt system.',
    coverPhoto: '/CAD/SolarPanelOnARoof/Solar-panels-on-flat-roof-1.jpeg',
    gltfFile: '/CAD/SolarPanelonaRoof/Unnamed6-assemFusion.gltf',
    color: '#90e0ef',
    modelColor: '#4169E1',
    modelRotation: { x: Math.PI / 2, y: 0, z: Math.PI / 2 },
    tags: ['Solar', 'Structure', 'Analysis'],
    transparency: 30
  },
  {
    id: 7,
    title: 'Solar Vortex Engine',
    category: 'Energy Systems',
    year: '2024',
    description: 'Research-grade CAD model with complete internal flow path designed for CFD studies.',
    coverPhoto: '/Projects/SVE/SVE (1).png',
    gltfFile: '/CAD/SVE/SVE.gltf',
    color: '#ffbe0b',
    modelColor: '#4e8eb9',
    modelRotation: { x: Math.PI / 2, y: 0, z: Math.PI / 2 },
    tags: ['Energy', 'CFD', 'Research'],
    transparency: 10
  },
  {
    id: 8,
    title: 'Tire Design',
    category: 'Automotive',
    year: '2024',
    description: 'Detailed tire model with realistic tread pattern and structural components for vehicle dynamics simulation.',
    coverPhoto: '/CAD/Tire/Tire.jpg',
    gltfFile: '/CAD/Tire/Tire.gltf',
    color: '#65ce45',
    modelColor: '#79acb3',
    modelRotation: { x: Math.PI / 2, y: 0, z: Math.PI / 2 },
    tags: ['Automotive', 'Simulation', 'Design'],
    transparency: 0
  },
  {
    id: 9,
    title: 'Toroidal Propeller',
    category: 'Advanced Aerodynamics',
    year: '2024',
    description: 'Novel toroidal propeller design for reduced noise and improved efficiency in drone applications.',
    coverPhoto: '/CAD/toroidalProp/ToroidalProp.png',
    gltfFile: '/CAD/toroidalProp/5040 NACA2415 Toroidal Propeller CCW.gltf',
    color: '#9d4edd',
    modelColor: '#e14184ff',
    modelRotation: { x: Math.PI / 2, y: 0, z: Math.PI / 2 },
    tags: ['Aero', 'Innovation', 'Noise Reduction'],
    transparency: 0
  },
  {
    id: 10,
    title: 'Truck Model',
    category: 'Transportation',
    year: '2024',
    description: 'Complete truck model for aerodynamic analysis and platooning simulations including cab and trailer.',
    coverPhoto: '/CAD/TruckModel/Truck.jpeg',
    gltfFile: '/CAD/TruckModel/Truck.gltf',
    color: '#ef233c',
    modelColor: '#e5f137ff',
    modelRotation: { x: Math.PI / 2, y: 0, z: Math.PI / 2 },
    tags: ['Transport', 'Aero', 'CFD'],
    transparency: 0
  },
  {
    id: 11,
    title: 'Wind Tunnel Section',
    category: 'Experimental Equipment',
    year: '2024',
    description: 'Precision 3D model of wind tunnel test section from field measurements with 0.01mm tolerance.',
    coverPhoto: '/Projects/CAD Modeling of Wind Tunnel Test Section/CAD Modeling of Wind Tunnel Test Section.jpg',
    gltfFile: '/CAD/WindTunnelModelling/Wind Tunnel.gltf',
    color: '#8338ec',
    modelColor: '#C0C0C0',
    modelRotation: { x: Math.PI / 2, y: 0, z: Math.PI / 2 },
    tags: ['Research', 'Precision', 'Experiment'],
    transparency: 30
  },
  {
    id: 12,
    title: 'CRT TV Model',
    category: 'Experimental Equipment',
    year: '2024',
    description: 'Precision 3D model of wind tunnel test section from field measurements with 0.01mm tolerance.',
    coverPhoto: '/Projects/CAD Modeling of Wind Tunnel Test Section/CAD Modeling of Wind Tunnel Test Section.jpg',
    gltfFile: '/SectionHelp/CAD/TV.gltf',
    color: '#8338ec',
    modelColor: '#C0C0C0',
    modelRotation: { x: Math.PI / 2, y: 0, z: Math.PI / 2 },
    tags: ['Research', 'Precision', 'Experiment'],
    transparency: 30
  },
]

export default CADGLTFList